pygments: true
#permalink: /otter-pop/:year/:month/:day/:title
markdown: rdiscount
exclude: ['.git']
name: "shane lahman hogle"
email: shane.hogle@gmail.com
twitter: slhogle
gitbub: slhogle
description: "marine microbial ecology, biogeochemistry, bioinformatics"
url: http://slhogle.github.io/
