highlighter: pygments
#permalink: /otter-pop/:year/:month/:day/:title
markdown: rdiscount
exclude: ['.git']
name: "shane hogle"
email: shane.hogle@gmail.com
twitter: slhogle
github: slhogle
description: "shane hogle"
url: http://slhogle.github.io/
